# Schema for the simple_timeline plugin.
views.style.simple_timeline:
  type: views_style
  label: 'Simple Timeline'
  mapping:
    wrapper_class:
      type: string
      label: 'Wrapper class'
    class:
      type: string
      label: 'List class'
    position_items:
      type: string
      label: 'Position items'
    position_marker:
      type: string
      label: 'Position marker'
